[package]
name = "watcher"
version = "0.1.0"
authors = ["Daniel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nvml-wrapper = "0.5.0"
web-view = { version = "0.5.4", features = ["edge"] }